[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
logfile_maxbytes=1MB
pidfile=/tmp/supervisord.pid

[program:api]
command=uvicorn main:app --host 0.0.0.0 --port 7860
directory=%(ENV_HOME)s/app
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:worker]
command=python -m worker.job_poller
directory=%(ENV_HOME)s/app
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
